### ISSUE TITLE
resize polygonal-hole.png

### ISSUE THREAD

**Issue by orias** [alephobjects/taz-docs#16]
Figure 2.64: Holes made through polygonal segments. is huge, and looks ugly.

**Comment by nickthetait** [comment]
Please excuse my ignorance. What are "polygonal segments"? Do you have a picture to help describe it? Lacking a bit of information on this issue.

**Comment by orias** [comment]
Hehe. The image is a small PNG and when rendered in the manual, it looks rough. I'm on this :D

**Comment by nickthetait** [comment]
:+1:

**Comment by orias** [comment]
.../slic3r/DimensionErrors.tex

**Comment by orias** [comment]
fixed with https://github.com/alephobjects/taz-docs/commit/e9d1517bbe7d614e4778dc6c2b1ededdddcdfea2
